package com.zaxxon.networking;

import java.net.InetAddress;
/**
 * Class where specific information about a client is being stored in.
 * @author Omar Farooq Khan
 *
 */
public class ServerClient {

	public String name;
	public InetAddress address;
	public int port;
	private int deaths =0 ;
	private final String ID;
	
	/**
	 * Constructor Used to set up a client that has joined the server.
	 * @param user username of the user.
	 * @param address IP address of the user.
	 * @param port Port the user connected from.
	 * @param ID Unique user ID generated by the server.
	 */
			
	public ServerClient(String user,InetAddress address, int port,String ID) {
		this.name = user;
		this.address = address;
		this.port = port;
		this.ID = ID;
	}

	/**
	 * getter for IP address of the client.
	 * @return IP address.
	 */
	public InetAddress getAddress() {
		return address;
	}

	/**
	 * getter for the port number of the client.
	 * @return port number of the client.
	 */
	public int getPort() {
		return port;
	}

	/**
	 * getter for the ID of the client.
	 * @return ID of the client.
	 */
	public String getID() {
		return ID;
	}
	/**
	 * Reset the clients deaths.
	 */
	public void resetDeaths() {
		deaths = 0;
	}
	/**
	 *  getter for client deaths.
	 * @return the number of times a client has died.
	 */
	public int getDeaths() {
		return deaths;
	}
	/**
	 * Method to increace clients deaths by 1.
	 * @return 
	 */
	public void incDeaths() {
		deaths +=1;
	}
}
